### ISSUE TITLE
Option for Carpet /player's to not drop heads

### ISSUE THREAD

**Issue by tesseract-two** [onebeastchris/fabricgeyserplayerheads#4]
Otherwise whenever you remove a /player you get a head, and they pile up fast. 
This appears to be how Carpet checks:
https://github.com/gnembon/fabric-carpet/blob/master/src/main/java/carpet/commands/PlayerCommand.java#L177

And this is the file that the above references:
https://github.com/gnembon/fabric-carpet/blob/master/src/main/java/carpet/patches/EntityPlayerMPFake.java

**Comment by onebeastchris** [comment]
Hey there!
First of, thanks for the bug report, especially for linking the files directly ^^

I unfortunately am currently not able to implement this feature - I'm on holidays, and 1.19.3 support is a tad more pressing, but I'll try to implement this. Assuming that it's possible to check whether a player is a carpet player or not. 

I'll keep you updated here!

**Comment by tesseract-two** [comment]
Of course, enjoy your holidays!

**Comment by onebeastchris** [comment]
https://modrinth.com/mod/geyserplayerheads/version/1.0.1
Hey, I've tried implementing such a check - could you test it?
You may need to regenerate your config to get the config option. Other than that, you should hopefully not get heads when killing a fake player. Sorry for the wait!

**Comment by tesseract-two** [comment]
Yup, it seems to be working. Thank you!

**Comment by onebeastchris** [comment]
yay, great
I'll close this issue; and if there are no bug reports for a few more days, I'll mark the new version as release :-)
Thanks again for the bug report, and sorry for the long wait
